// Generated by https://github.com/foxglove/schemas

import { ArrowPrimitive } from "./ArrowPrimitive";
import { ConePrimitive } from "./ConePrimitive";
import { CubePrimitive } from "./CubePrimitive";
import { LinePrimitive } from "./LinePrimitive";
import { ModelPrimitive } from "./ModelPrimitive";
import { PrimitiveDeletion } from "./PrimitiveDeletion";
import { SpherePrimitive } from "./SpherePrimitive";
import { TextPrimitive } from "./TextPrimitive";
import { TriangleListPrimitive } from "./TriangleListPrimitive";

/** A list of entities to be added, removed, or replaced in a 3D scene */
export type SceneUpdate = {
  /** Marker deletion actions */
  deletions: PrimitiveDeletion[];

  /** Arrow primitives */
  arrows: ArrowPrimitive[];

  /** Cube primitives */
  cubes: CubePrimitive[];

  /** Sphere primitives */
  spheres: SpherePrimitive[];

  /** Cone primitives */
  cones: ConePrimitive[];

  /** Line primitives */
  lines: LinePrimitive[];

  /** Triangle list primitives */
  triangles: TriangleListPrimitive[];

  /** Text primitives */
  texts: TextPrimitive[];

  /** Model primitives */
  models: ModelPrimitive[];
};
